name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  release:
    name: release
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PyPI_token: ${{ secrets.PyPI_TOKEN }}
